"""Provider interfaces for AgenticKVM."""

from agentickvm.providers.artifacts import (
    ArtifactPolicyError,
    ScreenshotArtifactPolicy,
)
from agentickvm.providers.base import (
    Provider,
    ProviderActionRequest,
    ProviderActionResult,
    ProviderStatus,
    ProviderValidationResult,
)
from agentickvm.providers.errors import (
    PROVIDER_ERROR_TYPES,
    ProviderAuthenticationFailedError,
    ProviderAuthenticationRequiredError,
    ProviderAuthorizationError,
    ProviderConfigError,
    ProviderConnectionError,
    ProviderDisabledError,
    ProviderError,
    ProviderErrorInfo,
    ProviderMutationBlockedError,
    ProviderNotFoundError,
    ProviderProtocolError,
    ProviderRateLimitedError,
    ProviderResponseValidationError,
    ProviderSecretRequiredError,
    ProviderTLSVerificationError,
    ProviderTimeoutError,
    ProviderUnsafeOperationError,
    TargetNotFoundError,
    UnsupportedCapabilityError,
)
from agentickvm.providers.mock import MockProvider
from agentickvm.providers.pikvm import (
    PIKVM_OBSERVE_CAPABILITIES,
    PiKVMObserveClient,
    PiKVMObserveProvider,
    default_pikvm_fake_transport,
)
from agentickvm.providers.pikvm_transport import (
    FakePiKVMObserveTransport,
    PiKVMLiveObserveTransportUnavailable,
    PiKVMObserveTransport,
    redact_pikvm_observe_payload,
)
from agentickvm.providers.placeholders import (
    DisabledRealProviderPlaceholder,
    OBSERVE_ONLY_REAL_PROVIDER_CAPABILITIES,
    PiKVMProviderPlaceholder,
    RealProviderNotEnabledError,
    RedfishProviderPlaceholder,
)
from agentickvm.providers.preflight import (
    LiveProviderPreflightRequest,
    LiveProviderPreflightResult,
    OBSERVE_ONLY_PROVIDER_TYPES,
    PreflightStatus,
    detected_ci_mode,
    detected_test_mode,
    run_live_provider_preflight,
)
from agentickvm.providers.redfish import (
    REDFISH_OBSERVE_CAPABILITIES,
    RedfishObserveClient,
    RedfishObserveProvider,
    default_redfish_fake_transport,
)
from agentickvm.providers.registry import (
    EXECUTABLE_PROVIDER_TYPES,
    KNOWN_PROVIDER_TYPES,
    PLACEHOLDER_PROVIDER_TYPES,
    ProviderEntry,
    ProviderRegistry,
    ProviderRegistryError,
)
from agentickvm.providers.transport_policy import (
    RETRYABLE_ERROR_CODES,
    UNSAFE_CAPABILITY_PREFIXES,
    TransportPolicyError,
    TransportSecurityPolicy,
)

__all__ = [
    "EXECUTABLE_PROVIDER_TYPES",
    "ArtifactPolicyError",
    "DisabledRealProviderPlaceholder",
    "FakePiKVMObserveTransport",
    "KNOWN_PROVIDER_TYPES",
    "MockProvider",
    "OBSERVE_ONLY_REAL_PROVIDER_CAPABILITIES",
    "OBSERVE_ONLY_PROVIDER_TYPES",
    "PIKVM_OBSERVE_CAPABILITIES",
    "PLACEHOLDER_PROVIDER_TYPES",
    "PiKVMProviderPlaceholder",
    "PiKVMLiveObserveTransportUnavailable",
    "PiKVMObserveClient",
    "PiKVMObserveProvider",
    "PiKVMObserveTransport",
    "PROVIDER_ERROR_TYPES",
    "Provider",
    "ProviderActionRequest",
    "ProviderActionResult",
    "ProviderAuthenticationFailedError",
    "ProviderAuthenticationRequiredError",
    "ProviderAuthorizationError",
    "ProviderConfigError",
    "ProviderConnectionError",
    "ProviderDisabledError",
    "ProviderError",
    "ProviderErrorInfo",
    "ProviderEntry",
    "LiveProviderPreflightRequest",
    "LiveProviderPreflightResult",
    "ProviderMutationBlockedError",
    "ProviderNotFoundError",
    "ProviderProtocolError",
    "ProviderRateLimitedError",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderResponseValidationError",
    "ProviderSecretRequiredError",
    "ProviderStatus",
    "ProviderTLSVerificationError",
    "ProviderTimeoutError",
    "ProviderUnsafeOperationError",
    "ProviderValidationResult",
    "REDFISH_OBSERVE_CAPABILITIES",
    "RETRYABLE_ERROR_CODES",
    "PreflightStatus",
    "RealProviderNotEnabledError",
    "RedfishObserveClient",
    "RedfishObserveProvider",
    "RedfishProviderPlaceholder",
    "ScreenshotArtifactPolicy",
    "TargetNotFoundError",
    "TransportPolicyError",
    "TransportSecurityPolicy",
    "UNSAFE_CAPABILITY_PREFIXES",
    "UnsupportedCapabilityError",
    "default_pikvm_fake_transport",
    "default_redfish_fake_transport",
    "detected_ci_mode",
    "detected_test_mode",
    "redact_pikvm_observe_payload",
    "run_live_provider_preflight",
]
